name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*
            pest: 1.*
          - laravel: 10.*
            testbench: 8.*
            pest: 2.*
          - laravel: 11.*
            testbench: 9.*
            pest: 2.*
        exclude:
          # Laravel 9 doesn't support PHP 8.3
          - php: 8.3
            laravel: 9.*
          # Laravel 10 requires PHP 8.1+
          - php: 8.0
            laravel: 10.*
          # Laravel 11 requires PHP 8.2+
          - php: 8.1
            laravel: 11.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, iconv, imagick, fileinfo, redis
          coverage: none

      - name: Install dependencies
        run: |
          composer config allow-plugins.pestphp/pest-plugin true
          composer config allow-plugins.pestphp/pest-plugin-laravel true
          
          # Install specific Pest version based on Laravel version
          if [[ "${{ matrix.laravel }}" == "9.*" ]]; then
            composer require "pestphp/pest:^1.22" "pestphp/pest-plugin-laravel:^1.4" --no-interaction --no-update
          else
            composer require "pestphp/pest:^2.0" "pestphp/pest-plugin-laravel:^2.0" --no-interaction --no-update
          fi
          
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        env:
          REDIS_CLIENT: phpredis
        run: |
          # Setup Redis for testing
          redis-cli FLUSHALL
          vendor/bin/pest